#!/bin/sh

user="${USER}@"
OS="$(lsb_release -sirc)"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed 's/Model\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
IP="$(hostname -I | awk '{print $1}')"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi

# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Light Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[38m" # Sky Blue
c9="\e[39m" # Light Grey
c10="\e[40m" # Dark Grey
c20="\e[0m" # Normal

# An Error echo Wrapper
err0r()
{
	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
	echo ""
	exit 86
}


# A Warning echo wrapper
warn ()
{
	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
	echo ""
}



# A Message echo Wrapper
msg ()
{
	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}


clear

echo ""
echo '          _,met$$$$$gg.        '
echo '       ,g$$$$$$$$$$$$$$$P.     '   ${c1}$user${c20}$(hostname)
echo '     ,g$$P""       """Y$$.".   '   ${c1}$envtype:  ${c20}$WM  			 
echo '    ,$$P"              `$$$."  '   ${c1}Kernel:  ${c20}$Kernel 
echo '   ,$$P       ,ggs.     `$$b:  '   ${c1}Uptime:  ${c20}$Uptime
echo '  `d$$"     ,$P""   .    $$$   '   ${c1}Packages:  ${c20}$Packages          
echo '   $$P      d$"     ,    $$P   '   ${c1}Shell:  ${c20}$Shell          
echo '   $$:      $$.   -    ,d$$"   '   ${c1}CPU:  ${c20}$CPU			            
echo '   $$\;      Y$b._   _,d$P     '   ${c1}GPU:  ${c20}$GPU	                 
echo '   Y$$.    `.`"Y$$$$P""        '	 ${c1}RAM:  ${c20}$RAM		        			 	                       
echo '   `$$b      "-.__             '   ${c1}IP:   ${c20}$IP
echo '    `Y$$                       '
echo '     `Y$$.                     '
echo '       `$$b.                   '
echo '         `Y$$b.                '
echo '            `"Y$b._            '
echo '                `""""          '
echo ""
