#!/bin/bash

#!/bin/bash

yad --form --center --undecorated --align=left --width=165 --borders=10 --height=320 --title="Exit" --skip-taskbar \
	--image=/usr/share/ldvuan/icons/Devuan-logo-white.png --image-on-top \
	--field="  Shutdown!gnome-shutdown!Shut Down":fbtn "loginctl poweroff" \
	--field="  Reboot!system-reboot!Restart":fbtn "loginctl reboot" \
	--field="  Log Out!gnome-logout!Log out":fbtn "loginctl terminate-user $USER" \
	--field="  Screen Lock!system-lock-screen!Lock the Screen":fbtn "lok"
	--button= gtk-cancel --buttons-layout=center \
