#!/bin/sh

user="${USER}@"
OS="$(lsb_release -sirc)"
#Desktop="${XDG_CURRENT_DESKTOP}"
Kernel="$(uname -sr)"
Uptime="$(uptime -p | sed 's/up //')"
Packages="$(dpkg -l | grep -c ^i)"
Shell="$(basename "$SHELL")"
CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed 's/Model\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"


if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='Desktop'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='Desktop'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'

fi

# COLORS
c1="\e[31m" # Red
c2="\e[32m" # Light Green
c3="\e[33m" # Yellow
c4="\e[34m" # Calm Blue
c5="\e[35m" # Violet
c6="\e[36m" # Arch Blue
c7="\e[37m" # White
c8="\e[38m" # Sky Blue
c9="\e[39m" # Light Grey
c10="\e[40m" # Dark Grey
c20="\e[0m" # Normal

# An Error echo Wrapper
err0r()
{
	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
	echo ""
	exit 86
}


# A Warning echo wrapper
warn ()
{
	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
	echo ""
}



# A Message echo Wrapper
msg ()
{
	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
}


echo ""
echo  "${c6}                       ;          	${c20}   __   _                 ___       __   __   __       		"
echo  "${c6}                       ED.         	${c20}  / /  (_)__  __ ____ __ / _ \___ _/ /  / /  / /__ ____		"
echo  "${c6}                       E#Wi        	${c20} / /__/ / _ \/ // /\ \ // // / _ \`/ _ \/ _ \/ / -_) __/		"
echo  "${c7}                   i  ${c6} E###G.      	${c20}/____/_/_//_/\_,_//_\_\/____/\_,_/_.__/_.__/_/\__/_/   		"
echo  "${c7}                  LE   ${c6}E#fD#W;     													"
echo  "${c7}                 L#E   ${c6}E#t t##L    	"				${c1}$user${c20}$(hostname)
echo  "${c7}                G#W.   ${c6}E#t  .E#K,  	"				${c1}OS:  ${c20}$OS
echo  "${c7}               D#K.    ${c6}E#t    j##f 	"				${c1}Kernel:  ${c20}$Kernel
echo  "${c7}              E#K.     ${c6}E#t    :E#K:	"				${c1}$envtype:  ${c20}$WM
echo  "${c7}            .E#E.      ${c6}E#t   t##L  	"				${c1}Uptime:  ${c20}$Uptime
echo  "${c7}           .K#E        ${c6}E#t .D#W;   	"				${c1}Packages:  ${c20}$Packages
echo  "${c7}          .K#D         ${c6}E#tiW#G.    	"				${c1}Shell:   ${c20}$Shell
echo  "${c7}         .W#G          ${c6}E#K##i      	"				${c1}CPU: ${c20}$CPU
echo  "${c7}        :W##########Wt ${c6}E##D.       	"				${c1}GPU: ${c20}$GPU
echo  "${c7}        :,,,,,,,,,,,,,.${c6}E#t         	"				${c1}RAM: ${c20}$RAM
echo  "${c7}                       ${c6}L:          	"
echo ""


