#!/bin/bash

DMENU='dmenu -i -l 4'
choice=$(echo -e "logout\nshutdown\nreboot\nquit-pmenu" | $DMENU)

case "$choice" in
	logout) pkill dwm ;;
	shutdown)sudo shutdown now ;;
	reboot) sudo reboot ;;
	quit-pmenu) exit 0 ;;
esac
