#!/bin/bash
# requires feh
# Script to automatically change the wallpaper and lock screen in spectrwm

# Directory Containing the Pictures
DIR="/usr/share/backgrounds"

# Command to Select wallpapers at random from the $DIR directory

WAL=$(ls $DIR/*.png | shuf -n1)

# Set lockscreen wallpaper

cat $WAL > $DIR/current-wallpaper.png

# Set Desktop Wallpaper

feh --bg-scale $DIR/current-wallpaper.png

